# Generated by Django 2.0 on 2017-12-16 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ('-created_at',)},
        ),
    ]
